# Generated by Django 3.2.6 on 2021-08-08 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210808_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='attendance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='home.attendance'),
        ),
        migrations.AlterField(
            model_name='education',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='home.location'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=600)),
                ('attendance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='home.attendance')),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='home.location')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.person')),
            ],
        ),
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=300)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.experience')),
            ],
        ),
    ]
